import Head from 'next/head'
import { InputSearchOpen } from '../components/inputSearchOpen'
import { OpenModalAnimation } from '../components/openModalAnimation'

export default function Home() {

   return (
      <>
         <Head>
         <title>Área de Testes </title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
         </Head>

         <div className={'flex flex-col gap-8 p-24 flex-1 items-center justify-center'}>
            <OpenModalAnimation/>
            
            <InputSearchOpen/>
         </div>
         
      </>
   )
}
